/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3ENOPENFEINT_AUTODEFS_H
#define S3ENOPENFEINT_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_NOPENFEINT_NAME "s3eNOpenFeint"
#define S3E_EXT_NOPENFEINT_HASH 0x74c89566

#endif /* !S3ENOPENFEINT_AUTODEFS_H */
